### ISSUE TITLE
ios启动的问题

### ISSUE THREAD

**Issue by XzyZachary** [funnyzak/ChatMate-GPT#12]
PhaseScriptExecution [CP-User]\ Generate\ Specs /Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-46EB2E000239C0.sh (in target 'FBReactNativeSpec' from project 'Pods')

最近想学习下您这个项目，我yarn ios的时候报上面这个错，请问是为什么？

**Comment by funnyzak** [comment]
可能是环境问题，我的环境是 Node18、XCode 14.3，检查下环境，然后清缓存，重新安装依赖并编译试试。
