### ISSUE TITLE
APP安装问题：Safari浏览器打不开该网页，因为网址无效。

### ISSUE THREAD

**Issue by unclegpts** [funnyzak/ChatMate-GPT#14]
将网址复制到Safari浏览器打开，无法正常安装！需要开发者检查一下链接是否正确？谢谢！

**Comment by unclegpts** [comment]
IOS和Android均已安装了，但是添加了自己的API Server服务器和密钥后，验证并保存时提示：Request failed,maybe the API key is invalid。可以确定API服务器与密钥是正确无误且有效的（其他第三方应用使用正常）。目前IOS和Android都出现了这个情况，希望尽快解决，辛苦了！

**Comment by funnyzak** [comment]
这个问题一般是请求api server验证失败，你添加并设置API Server为：`https://openai.chat-mate.app`，然后再验证试试。

**Comment by unclegpts** [comment]
> 这个问题一般是请求API Server验证失败，你添加并设置API Server为：，然后再验证试试。`https://openai.chat-mate.app`

设置了你们的API Server服务器（`https://openai.chat-mate.app）也不行，还是提示：Request failed,maybe the API key is invalid。

**Comment by funnyzak** [comment]
@unclegpts 长按保存key按钮，免验证保存key

**Comment by unclegpts** [comment]
> 这个问题一般是请求api server验证失败，你添加并设置API Server为：`https://openai.chat-mate.app`，然后再验证试试。

用你提供的方法已经可以正常使用了，只是花费（token额度）还识别不到（具体原因不清楚）。你是否可以参考https://github.com/Yidadaa/ChatGPT-Next-Web里的功能，最终来实现余额（token额度）查询。谢谢！

**Comment by unclegpts** [comment]
> @unclegpts 验证Key是通过请求 api.openai.com 进行的。 你可以在设置 apikey 配置页，长按`保存key`按钮，免验证保存key。

用你提供的方法已经可以正常使用了，只是花费（token额度）还识别不到（具体原因不清楚）。你是否可以参考https://github.com/Yidadaa/ChatGPT-Next-Web/里的功能，最终来实现余额（token额度）查询。谢谢！
![微信图片_20230601160709](https://github.com/funnyzak/ChatMate-GPT/assets/132789586/4cfbff07-42d0-478d-ab58-75cd47ee7116)

**Comment by funnyzak** [comment]
@unclegpts 验证这个问题，后续升级调整下。

余额查询功能开发的时候，使用的是免费额度，没有测试付费账号的数据返回格式。再下一版会调整下。

**Comment by Devenke6** [comment]
太强悍了，话术遇引导有时候会卡，还有一个就是大佬能不能加上软件的语音功能.或者辛苦一下加上语音唤醒 ，不是手机界面的唤醒，是在软件内唤醒这样更简便

**Comment by funnyzak** [comment]
> 太强悍了，话术遇引导有时候会卡，还有一个就是大佬能不能加上软件的语音功能.或者辛苦一下加上语音唤醒 ，不是手机界面的唤醒，是在软件内唤醒这样更简便

这个功能只能考虑后续增加了，目前会考虑优先支持其他平台的api。
